package com.entity.resolution.core.model;

/**
 * Source of a synonym in the entity resolution system.
 */
public enum SynonymSource {
    /**
     * Synonym generated by the system through normalization rules.
     */
    SYSTEM,

    /**
     * Synonym added by a human operator.
     */
    HUMAN,

    /**
     * Synonym suggested by an LLM and approved.
     * Per PRD 7.2, LLMs never perform direct merges but can suggest synonyms.
     */
    LLM
}
